os:
  - linux
  - osx

env:
  matrix:
    - export NODE_VERSION="4" CC=clang CXX=clang++ npm_config_clang=1
    - export NODE_VERSION="6" CC=clang CXX=clang++ npm_config_clang=1
    - export NODE_VERSION="7" CC=clang CXX=clang++ npm_config_clang=1

install:
- npm install

script: "npm run-script test-cover"

# Send coverage data to Coveralls
after_script: "cat ./docs/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"