// Imports
const packageDefault = require("../default/package.json");

function createPackageJson(options={}) {

    let defaults = {
        name: "Untitled",
        version: "0.0.0",
        description: "A new project generated by the Warhorse task runner.",
        keywords: ["javascript"],
        author: "Unknown",
        license: "GPL-3.0"
    };

    let packageConfig = Object.assign(packageDefault, options);
    console.log(JSON.stringify(packageConfig));
    return packageConfig;
}

// Exports
// module.exports = createPackageJson;

createPackageJson({name: "warhorse", author: "Kyle Sargeant", keywords: ["some", "test"]});
